### ISSUE TITLE
how to get filepath outside of  base64ToFile.convert function

### ISSUE THREAD

**Issue by chandrasekarb** [viamgr/base64ToFile#1]
function len(params) {
	var ss;
	base64ToFile.convert(params.imgvalue,"demo/",['jpg','jpeg','png'], function (filePath) {
		console.log('**file:** '+filePath);
		var a=filePath;
		ss=a;
		});
	var user =ss;
	console.log('**user:** '+user);
	return user;
}

hi I'm using this code it's working but how to get **filepath** outside of **base64ToFile.convert** function

my output is

**user:** undefined
**file:** demo/image-df1d03c4b6dc6665f841f1065a2acc981f14182e.png

please anybody give the solution...

**Comment by viamgr** [comment]
The base64ToFile plugin just works in non-blocking mode.To achieve your goal you have to use a callback to return converted image. another ugly way is DeAsync library: [https://github.com/abbr/deasync]( https://github.com/abbr/deasync)
